import java.util.List;
import java.util.ArrayList;

public class App {
    /*
     * Problem statement:
     * The sequence of triangle numbers is generated by adding the natural numbers.
     * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
     * ten terms would be:
     * 
     * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
     * 
     * Let us list the factors of the first seven triangle numbers:
     * 
     * 1: 1
     * 3: 1,3
     * 6: 1,2,3,6
     * 10: 1,2,5,10
     * 15: 1,3,5,15
     * 21: 1,3,7,21
     * 28: 1,2,4,7,14,28
     * We can see that 28 is the first triangle number to have over five divisors.
     * 
     * What is the value of the first triangle number to have over five hundred
     * divisors?
     */
    public static void main(String[] args) {
        long j = 0L;
        int k = 0;
        List<Long> factors = new ArrayList<Long>();

        for (int i = 1; i < limit; i++) {
            while (k <= 500) {
                j = calculateTheNextTriangleNumber(i);
                factors = determineFactorsOfThatTriangleNumber(j);
                k = determineTheQuantityOfFactorsForThatTN(factors);
                // stop when first triangle number has 501+ factors (i.e. > 500) - these are NOT
                // base factors,
                // but rather ALL factors (multiples count - so all EVEN numbers are included,
                // even though
                // they are all multiples of 2)
            }
        }
        System.out.println("First triangle number with over 500 factors is: " + j + ", with " + k + " factors");
    }

    private static long calculateTheNextTriangleNumber(int numberOfTriangleNumber) {
        long sum = 0;
        for (int i = 0; i < numberOfTriangleNumber; i++) {
            sum += i;
        }
        return sum;
    }

    private static List<Integer> determineFactorsOfThatTriangleNumber(int triangleNumber) {
        ArrayList<Integer> factors = new ArrayList<Integer>();
        int numPrime = 0;
        Boolean divisible = false;
        for (int i = 1; triangleNumber; i++) {
            for (int j = 1; j < i; j++) {
                if (i % j == 0) {
                    factors.add(i);
                }
            }
        }
        return factors;
    }

    private static int determineTheQuantityOfFactorsForThatTN(List<Integer> factors) {
        return factors.size();
    }
}
